

const EVENTS = [
  {
    id: "wds-2026",
    no: "0142",
    title: "Web Development Workshop",
    category: "Workshop",
    bannerClass: "banner-workshop",
    icon: "bi-code-slash",
    date: "15 July 2026",
    time: "09:00 AM – 01:00 PM",
    venue: "Main Hall, Faculty of ICT",
    organizer: "ICT Students' Association",
    remaining: 65,
    capacity: 100,
    rating: 4.2,
    ratingCount: 32,
    description:
      "A hands-on session covering HTML, CSS, JavaScript, PHP and MySQL through real project work — built for students who want to go from tutorials to shipped projects.",
    highlights: [
      "Hands-on practical sessions",
      "Certificate for all participants",
      "Networking opportunities",
      "Refreshments will be provided",
    ],
  },
  {
    id: "sports-meet-2026",
    no: "0143",
    title: "Inter University Sports Meet",
    category: "Sports",
    bannerClass: "banner-sports",
    icon: "bi-trophy",
    date: "20 July 2026",
    time: "08:00 AM – 06:00 PM",
    venue: "University Sports Complex",
    organizer: "Sports Council",
    remaining: 40,
    capacity: 250,
    rating: 4.6,
    ratingCount: 58,
    description:
      "Track, field and team-sport finals between faculties, capped off with the annual inter-university trophy presentation.",
    highlights: [
      "Live scoreboards on-site",
      "Team merchandise stalls",
      "Free entry for students",
      "Medal ceremony at 5:30 PM",
    ],
  },
  {
    id: "cultural-night-2026",
    no: "0144",
    title: "Cultural Night 2026",
    category: "Cultural",
    bannerClass: "banner-cultural",
    icon: "bi-stars",
    date: "25 July 2026",
    time: "06:00 PM – 10:00 PM",
    venue: "University Auditorium",
    organizer: "Cultural Club",
    remaining: 120,
    capacity: 400,
    rating: 4.8,
    ratingCount: 91,
    description:
      "An evening of dance, music and drama celebrating Sri Lanka's cultural diversity, hosted by every faculty society on campus.",
    highlights: [
      "Performances from 12 societies",
      "Food stalls from 5:30 PM",
      "Photography corner",
      "Best act audience award",
    ],
  },
  {
    id: "photo-meetup-2026",
    no: "0145",
    title: "Photography Club Meetup",
    category: "Club Activities",
    bannerClass: "banner-club",
    icon: "bi-camera",
    date: "02 August 2026",
    time: "03:00 PM – 05:30 PM",
    venue: "Faculty Courtyard",
    organizer: "Photography Society",
    remaining: 18,
    capacity: 40,
    rating: 4.4,
    ratingCount: 21,
    description:
      "A casual golden-hour shoot and critique session for the Photography Society — bring any camera, phones welcome.",
    highlights: [
      "Beginner-friendly",
      "Gear demo table",
      "Print exhibition sign-ups",
      "Light refreshments",
    ],
  },
  {
    id: "career-seminar-2026",
    no: "0146",
    title: "Career Readiness Seminar",
    category: "Seminar",
    bannerClass: "banner-workshop",
    icon: "bi-briefcase",
    date: "08 August 2026",
    time: "10:00 AM – 12:30 PM",
    venue: "Lecture Hall B",
    organizer: "Career Guidance Unit",
    remaining: 74,
    capacity: 150,
    rating: 4.1,
    ratingCount: 27,
    description:
      "Industry panelists walk through CVs, interviews and internship pathways for final-year ICT undergraduates.",
    highlights: [
      "Panel Q&A",
      "CV clinic sign-up sheet",
      "Internship listings shared",
      "Certificate of attendance",
    ],
  },
  {
    id: "robotics-showcase-2026",
    no: "0147",
    title: "Robotics Society Showcase",
    category: "Club Activities",
    bannerClass: "banner-club",
    icon: "bi-cpu",
    date: "14 August 2026",
    time: "11:00 AM – 04:00 PM",
    venue: "Innovation Lab",
    organizer: "Robotics Society",
    remaining: 55,
    capacity: 80,
    rating: 4.7,
    ratingCount: 34,
    description:
      "Student teams demo line-followers, arms and autonomous bots built this semester, with a live audience-choice vote.",
    highlights: [
      "Live robot demos",
      "Audience-choice award",
      "Open workshop tour",
      "Recruitment sign-ups",
    ],
  },
];

function getEventById(id) {
  return EVENTS.find((e) => e.id === id);
}
